#!/bin/bash
# shellcheck shell=bash
# https://github.com/linuxserver/docker-wireguard/blob/master/root/app/show-peer
# This file has been modified from the above source: paths were changed to be relative to the project root

if [[ ! $# -gt 0 ]]; then
  echo "You need to specify which peers to show"
  exit 0
fi

for i in "$@"; do
  if [[ "${i}" =~ ^[0-9]+$ ]]; then
    PEER_ID="peer${i}"
  else
    PEER_ID="peer_${i//[^[:alnum:]_-]/}"
  fi

  if grep -q "# ${PEER_ID}" wireguard/config/wg_confs/wg0.conf; then
    echo "PEER ${i} QR code:"
    qrencode -t ansiutf8 < wireguard/config/"${PEER_ID}"/"${PEER_ID}".conf
    echo "PEER ${i} config:"
    cat wireguard/config/"${PEER_ID}"/"${PEER_ID}".conf
  else
    echo "PEER ${i} is not active"
  fi
done