#!/bin/bash
# shellcheck disable=SC1091

pushd /opt/closure || exit 1
[ ! -f installed ] || rm -rf installed
[[ ! -f /etc/rc.local || -f /etc/rc.local.bak ]] || sudo mv -f /etc/rc.local /etc/rc.local.bak
cp -f rc.local /etc/rc.local
source "bs.sh"
popd || exit 1
