on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build package
        id: build
        run: |
          sed -i "s,^Description:,Files:$(find . -type f | grep -oP '(?<=^\./).*' | grep -vP '^(\.|debian/)' | while read -r file; do echo -e " $file /opt/closure/$file"; done | grep -oP '.*(?=/)' | awk -v ORS='\\n' '1')Description:," debian/control
          sudo apt-get update
          sudo apt-get install -y equivs
          equivs-build debian/control
          echo -e "built=$?\ntag=$(grep -oP '(?<=^Version: ).*' debian/control)\n" >> "$GITHUB_OUTPUT"

      - name: Create release
        if: ${{ steps.build.outputs.built == '0' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.deb"
          body: "Please see the README for any changes."
          tag: "v${{ steps.build.outputs.tag }}"
          commit: "master"
          allowUpdates: true
